### ISSUE TITLE
录制视频不足一秒的时候会报这个错误 Muxer stop failed

### ISSUE THREAD

**Issue by ellisonchan** [ellisonchan/JetpackDemo#1]
来自CSDN网友的report。

**Comment by ellisonchan** [comment]
我试了几次录制视频不足一秒但没复现，都能录制成功。

1.你报的错是OnVideoSavedCallback#onError()里回传的msg吧？
"Muxer stop failed!"是VideoCapture#videoEncode()里报出来的，这个函数是异步执行的。

感觉是异步处理视频编码的时候拿到了错误的mMuxerStarted值，并执行了stop处理。
在MediaMuxer尚未start的情况下开始stop即发生了异常。

2.据此判断的话，这个问题应该不是每次都复现吧？

3.另外stop发生异常的堆栈里包含MediaMuxer出错的状态原因，你看下onError()的Throwable里打印的状态是什么？
是不是INITIALIZED？

4.有一点值得提醒下，VideoCapture用例在CameraX中仍旧是hide API,仍然处在开发阶段。所以内部的实现并不稳定。

**Comment by lizhAndroid** [comment]
你好，报错是在OnVideoSavedCallback回调里返回的，我没有找到返回的状态原因，不过从断点上看状态应该是MUXER_STATE_STARTED，而且这个问题确实是每次都能复现，而且都会生成一个无法播放的的视频文件，而且我刚才测试了一下，你的demo也会这样，你可以试一下快速的点击播放按钮，大概几十毫秒这样，你的demo也会打印出错误信息的`2021-03-28 11:51:57.737 18905-18905/com.ellison.jetpackdemo D/Camera: onError videoCaptureError:2 message:Muxer stop failed!`

**Comment by ellisonchan** [comment]
> 你好，报错是在OnVideoSavedCallback回调里返回的，我没有找到返回的状态原因，不过从断点上看状态应该是MUXER_STATE_STARTED，而且这个问题确实是每次都能复现，而且都会生成一个无法播放的的视频文件，而且我刚才测试了一下，你的demo也会这样，你可以试一下快速的点击播放按钮，大概几十毫秒这样，你的demo也会打印出错误信息的`2021-03-28 11:51:57.737 18905-18905/com.ellison.jetpackdemo D/Camera: onError videoCaptureError:2 message:Muxer stop failed!`

快速点击record确实会复现。

LOG:
03-28 13:07:00.067 23270 23270 D Camera  : recordVideo
03-28 13:07:00.067 23270 23270 D Camera  : startRecording
03-28 13:07:00.078 23270 23270 D Camera  : onError videoCaptureError:3 message:It is still in video recording!
03-28 13:07:00.081 23270 23270 D Camera  : onError videoCaptureError:2 message:Muxer stop failed!
03-28 13:07:00.081 23270 23270 D Camera  : java.lang.IllegalStateException: Failed to stop the muxer
03-28 13:07:00.081 23270 23270 D Camera  :      at android.media.MediaMuxer.nativeStop(Native Method)
03-28 13:07:00.081 23270 23270 D Camera  :      at android.media.MediaMuxer.stop(MediaMuxer.java:454)
03-28 13:07:00.081 23270 23270 D Camera  :      at androidx.camera.core.VideoCapture.videoEncode(VideoCapture.java:787)
03-28 13:07:00.081 23270 23270 D Camera  :      at androidx.camera.core.VideoCapture.lambda$startRecording$4$VideoCapture(VideoCapture.java:449)
...

原因:
在于stopRecording是异步处理，频繁点击record的时候stop尚未结束却就又执行了start，导致出错。

暂定的回避方案：
startRecording没有提供回调，唯一可用的StateChangeCallback也不对外公开。

所以只能依据OnVideoSavedCallback的是否回调来决定是否可以再次startRecording。
在此期间，将record button置为disabled状态。
（参考我最近的一次提交）

备注：
新的方案上极为快速的点击record的时候，偶然情况下仍有发生:Muxer stop failed!异常的可能。
我推测是内部并行的视频编码的状态出了问题，暂时没有更好的办法。

**Comment by lizhAndroid** [comment]
你好，stop之后并没有再去start依然会报这个错，只需要快速停止就会出现这个问题，估计是stop那一步就已经出问题了，我暂时的解决方案只能先在onError回调中把生成的错误文件删掉了，希望后面会有解决的方案出来吧

**Comment by ellisonchan** [comment]
> 你好，stop之后并没有再去start依然会报这个错，只需要快速停止就会出现这个问题，估计是stop那一步就已经出问题了，我暂时的解决方案只能先在onError回调中把生成的错误文件删掉了，希望后面会有解决的方案出来吧

点击record时候快速点击停止即后面不再继续start的步骤，我试了多次，在新版本上没有复现。
可能存在概率性或一旦复现复现率很高的可能性。

从代码上看Muxer stop failed!的抛出地方，只存在于startRecording启动的videoEncode线程里。
而Muxer的使用还存在于audioEncode线程里。

音频和视频在编码的过程中主线程发出停止请求后两个线程里共用的Muxer 释放出错。。。
这是我的猜测。。。

官方的CameraX示例里也没有展示VideoCapture的使用。感觉这个API距离稳定仍很遥远。
https://github.com/android/camera-samples/tree/main/CameraXBasic

除了将出错后的视频文件删除，能否给recording状态下快速click抑制掉，比如500ms无视不允许点击停止。
你可以将相关修正merge上来。

**Comment by lizhAndroid** [comment]
不允许点击停止在体验上可能不好，可以根据时间不达一秒转为拍照功能，还是等官方公开文档吧，在此谢谢您的不吝赐教,感谢！
